name:                delta-stepping
version:             0.1.0.0
github:              "githubuser/delta-stepping"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/delta-stepping#readme>

dependencies:
- base >= 4.17 && < 5
- containers
- directory
- fgl
- fgl-visualize
- filepath
- primitive
- process
- stm
- vector
- split

ghc-options:
- -O2
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields

library:
  source-dirs: src

tests:
  delta-stepping:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -with-rtsopts=-T
    dependencies:
      - delta-stepping
      - hedgehog
      - tasty >= 1.2.2
      - tasty-bench >= 0.3.2
      - tasty-hedgehog

# vim: nospell
